### ISSUE TITLE
Distance of annotation bars to the graph can be set to max. 1

### ISSUE THREAD

**Issue by NinaSchukraft** [DSegebarth/dcl_stats_n_plots#15]

**Comment by NinaSchukraft** [comment]
![image](https://user-images.githubusercontent.com/104767253/168266840-4f1b55ea-9ef9-421c-95bb-f05ce7bb215d.png)

**Comment by NinaSchukraft** [comment]
I guess there is a general problem with the distance of the annotation bars, can not be adjusted and by default increase the y-axis so much that plot is hard to interpret

**Comment by DennisDoll** [comment]
Right. So the maximal value that can be chosen for the "Distance of the annotation bars to the graph" is 1. Let me explain what it actually means: 

Your data is screened for the maximal value & the annotation bars are plotted at the y-axis coordinate of this maximal value times the "Distance of the annotation bars to the graph". It therefore serves as a factor to scale the distance. If it is set to 0, the annotation bars will be plotted at the y-axis coordinate of your maximum value. If it is set to 0.1, the annotation bars will be plotted with a distance of max value * 0.1 between each other and above the maximum value.

When trying to reproduce something that might be similar to your issue, I was actually able to adjust it using the two customization features "Distance of the annotation bars to the graph" (use this one first!) and then, if necessary, adjust also the "Distance of the stars to the annotation bars". Since I know, that you are operating on very small plots, I tried to also resemble this. The following plot has a size of 5 x 4 cm and the fontsizes range between 6 (tick labels) and 8 (axis labels).

Before: Distance annotation bars = 1; Distance stars = 0.2
![grafik](https://user-images.githubusercontent.com/64020372/168401963-3844f832-fbb7-4bc9-8a3d-0f533efdae32.png)


After: Distance annotation bars = 0.1; Distance stars = 0.2
![grafik](https://user-images.githubusercontent.com/64020372/168402042-ab97a7bb-1085-4bb5-8aaf-6082d4f3fc8a.png)
