### ISSUE TITLE
Stripplots - data point clouds are too close to axes (left)/figure edge (right)

### ISSUE THREAD

**Issue by NinaSchukraft** [DSegebarth/dcl_stats_n_plots#16]
It would be better, if point clouds of stripplot would be equally dirstibuted along x-axis
![Unbenannt](https://user-images.githubusercontent.com/104767253/168266492-2926a546-dc20-4bf5-a201-f4e58f3855da.JPG)

**Comment by DennisDoll** [comment]
Could you elaborate a little more on when this happens? This would allow recreating the problem to see what changes to the code might fix this unwanted behavior. Seems to be the case if the plot gets really tiny?

**Comment by NinaSchukraft** [comment]
I don't think that it has something to do with the size, but rather with the statistic annotations. As soon as I tick a comparison, the points of the stripplot move apart.

**Comment by DennisDoll** [comment]
Good catch! The information that this happens when you toggle annotations on / off was exactly what was needed. Matplotlib re-scaled the x-axis automatically when the text for the annotation was plotted onto the figure, which is why the plots seemed to be drifting apart (actually the plot got zoomed in, you could say). X-axis scaling is stable from the current release (v0.2.5) on - thanks for noticing & reporting!
